name: mini_canvas
description: Canvas completed widgets. Such as pentagram, dashboard, dial, etc.
repository: https://github.com/collectFlutter/mini_canvas/tree/null-safety
version: 3.0.3

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

